"""
SPETS SECURITY — KeyCRM Integration
Creates Buyer + Order in KeyCRM after a quote is generated by the bot.

API: https://openapi.keycrm.app/v1
Docs: https://docs.keycrm.app
"""
import os
import logging
import requests
from typing import Optional

log = logging.getLogger(__name__)

API_KEY = os.getenv("KEYCRM_API_KEY", "")
BASE_URL = "https://openapi.keycrm.app/v1"

# IDs from KeyCRM (configured via env vars so we can change without code edit)
SOURCE_ID = int(os.getenv("KEYCRM_SOURCE_ID", "23"))            # Telegram Bot CCTV
MANAGER_ID = int(os.getenv("KEYCRM_MANAGER_ID", "0"))           # Oleksandr — set after diagnose
DEFAULT_ORDER_STATUS_ID = int(os.getenv("KEYCRM_STATUS_ID", "0"))  # "Новий" — set after diagnose

# Custom field IDs (from our diagnose)
CT_LANGUAGE = "CT_1029"   # Buyer Language
CT_COMPANY = "CT_1030"    # Buyer Company (we use for object type)
CT_CHANNEL = "CT_1001"    # Buyer Channel
OR_DISCOUNT = "OR_1010"   # Order Discount
OR_JOB_REF = "OR_1011"    # Order job reference (we use for quote number)


def _request(method: str, endpoint: str, payload: dict = None, params: dict = None) -> dict:
    """Helper for KeyCRM API requests."""
    if not API_KEY:
        log.error("KEYCRM_API_KEY not set")
        return {"error": "API key missing"}

    url = f"{BASE_URL}{endpoint}"
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    try:
        if method == "GET":
            r = requests.get(url, headers=headers, params=params or {}, timeout=20)
        elif method == "POST":
            r = requests.post(url, headers=headers, json=payload, timeout=20)
        elif method == "PUT":
            r = requests.put(url, headers=headers, json=payload, timeout=20)
        else:
            return {"error": f"Unknown method {method}"}

        if 200 <= r.status_code < 300:
            return r.json() if r.text else {}
        else:
            log.error(f"KeyCRM {method} {endpoint} failed: HTTP {r.status_code}")
            log.error(f"Response: {r.text[:500]}")
            return {"error": f"HTTP {r.status_code}", "body": r.text}
    except requests.RequestException as e:
        log.error(f"KeyCRM request failed: {e}")
        return {"error": str(e)}


def create_buyer(customer: dict, lang: str = "en") -> Optional[int]:
    """
    Create a buyer in KeyCRM.
    Returns buyer_id on success, None on failure.

    customer = {
        "name": "...",
        "phone": "+44...",
        "email": "...@...",
        "address": "..." (optional),
        "object_type": "House" (optional),
    }
    """
    payload = {
        "full_name": customer.get("name", "Client"),
        "phones": [customer["phone"]] if customer.get("phone") else [],
        "emails": [customer["email"]] if customer.get("email") else [],
        "custom_fields": [
            {"uuid": CT_LANGUAGE, "value": lang},
        ],
    }

    # Object type → Company field
    if customer.get("object_type"):
        payload["custom_fields"].append({
            "uuid": CT_COMPANY,
            "value": customer["object_type"],
        })

    # Channel → "Telegram Bot"
    payload["custom_fields"].append({
        "uuid": CT_CHANNEL,
        "value": "Telegram Bot",
    })

    if MANAGER_ID:
        payload["manager_id"] = MANAGER_ID

    result = _request("POST", "/buyer", payload=payload)
    if "error" in result:
        log.error(f"Failed to create buyer: {result}")
        return None

    buyer_id = result.get("id")
    log.info(f"Buyer created: id={buyer_id}, name={customer.get('name')}")
    return buyer_id


def create_order(
    buyer_id: int,
    quote_number: str,
    quote_items: list,
    grand_total: float,
    customer_address: str = "",
    lang: str = "en",
    job_reference: Optional[str] = None,
    customer: Optional[dict] = None,
) -> Optional[int]:
    """
    Create an order in KeyCRM linked to a buyer.
    Returns order_id on success, None on failure.
    """
    # Build products list
    products = []
    for item in quote_items:
        unit_price_with_vat = item["base"] + item["vat"]
        products.append({
            "name": item["name"],
            "sku": item.get("sku", ""),
            "price": round(unit_price_with_vat, 2),
            "quantity": item["qty"],
        })

    # Build buyer block — pass FULL contact info (no id) so KeyCRM populates
    # email/phone fields on the order page. KeyCRM will reuse the existing
    # buyer if email/phone matches; otherwise creates a new one.
    # IMPORTANT: do NOT pass buyer.id — it overrides email/phone fields.
    buyer_block: dict = {}
    if customer:
        if customer.get("name"):
            buyer_block["full_name"] = customer["name"]
        if customer.get("phone"):
            buyer_block["phone"] = customer["phone"]
        if customer.get("email"):
            buyer_block["email"] = customer["email"]
    # Fallback: if no customer info passed, link by id (legacy)
    if not buyer_block:
        buyer_block = {"id": buyer_id}

    payload = {
        "source_id": SOURCE_ID,
        "buyer": buyer_block,
        "products": products,
        "grand_total": round(grand_total, 2),
        "custom_fields": [
            {"uuid": OR_JOB_REF, "value": job_reference or f"Quote-{quote_number}"},
        ],
    }

    if MANAGER_ID:
        payload["manager_id"] = MANAGER_ID

    if DEFAULT_ORDER_STATUS_ID:
        payload["status_id"] = DEFAULT_ORDER_STATUS_ID

    # Shipping (delivery) address — KeyCRM uses specific field names
    if customer_address:
        payload["shipping"] = {
            "shipping_secondary_line": customer_address,
            "recipient_full_name": (customer.get("name") if customer else "") or "",
            "recipient_phone": (customer.get("phone") if customer else "") or "",
        }

    result = _request("POST", "/order", payload=payload)
    if "error" in result:
        log.error(f"Failed to create order: {result}")
        return None

    order_id = result.get("id")
    log.info(f"Order created: id={order_id}, buyer={buyer_id}, total=£{grand_total}")
    return order_id


def get_next_quote_number() -> Optional[int]:
    """
    Fetch the latest order number from KeyCRM and return next number (+1).
    Returns None if cannot fetch (caller should fall back to local counter).

    KeyCRM /order endpoint returns orders sorted by ID desc by default,
    so we just take the first one's id.
    """
    if not API_KEY:
        return None

    result = _request("GET", "/order", params={"limit": 1, "sort": "-id"})
    if "error" in result:
        log.warning(f"Could not fetch latest order from KeyCRM: {result.get('error')}")
        return None

    orders = result.get("data", [])
    if not orders:
        log.info("No orders in KeyCRM yet, starting from 1")
        return 1

    latest_id = orders[0].get("id", 0)
    next_num = int(latest_id) + 1
    log.info(f"Next quote number from KeyCRM: {next_num} (latest was {latest_id})")
    return next_num


def push_quote_to_keycrm(quote_data: dict) -> dict:
    """
    Create 3 orders in KeyCRM — one for each package (Budget, Balance, Elite).
    All 3 orders are linked to the same buyer (KeyCRM auto-matches by email/phone).

    quote_data structure (from bot.py):
    {
        "customer": {"name", "phone", "email", "address", "object_type"},
        "quote_number": "201",
        "lang": "uk",
        "packages": {
            "budget":  {"items": [...], "grand_total": 1317.54, "label": "Budget"},
            "balance": {"items": [...], "grand_total": 1959.92, "label": "Balance"},
            "elite":   {"items": [...], "grand_total": 2332.52, "label": "Elite"},
        },
    }

    Returns:
    {
        "ok": True/False,
        "order_ids": {"budget": 195, "balance": 196, "elite": 197},
        "main_order_id": 195  (first one, used for URL),
        "url": "...",
        "error": str if any,
    }
    """
    if not API_KEY:
        log.warning("KeyCRM disabled (no API key) — skipping CRM push")
        return {"ok": False, "error": "KEYCRM_API_KEY not configured"}

    customer = quote_data["customer"]
    lang = quote_data.get("lang", "en")
    packages = quote_data.get("packages", {})
    qn = quote_data["quote_number"]

    if not packages:
        return {"ok": False, "error": "no packages provided"}

    order_ids = {}
    errors = []

    # Create one order per package in order: Budget → Balance → Elite
    for pkg_id in ("budget", "balance", "elite"):
        if pkg_id not in packages:
            continue

        pkg = packages[pkg_id]
        pkg_label = pkg.get("label", pkg_id.capitalize())
        job_ref = f"Quote-{qn} | {pkg_label} package | £{pkg['grand_total']:.2f}"

        order_id = create_order(
            buyer_id=0,  # KeyCRM auto-matches via email/phone
            quote_number=qn,
            quote_items=pkg["items"],
            grand_total=pkg["grand_total"],
            customer_address=customer.get("address", ""),
            lang=lang,
            job_reference=job_ref,
            customer=customer,
        )

        if order_id:
            order_ids[pkg_id] = order_id
            log.info(f"Order #{order_id} created for {pkg_label}")
        else:
            errors.append(f"{pkg_label}: order creation failed")
            log.error(f"Failed to create {pkg_label} order")

    if not order_ids:
        return {"ok": False, "error": "; ".join(errors) or "all orders failed"}

    # Use the first order as the "main" one for URL / quote_number
    main_order_id = order_ids.get("budget") or order_ids.get("balance") or order_ids.get("elite")

    return {
        "ok": True,
        "order_ids": order_ids,
        "main_order_id": main_order_id,
        "order_id": main_order_id,  # backwards compatibility
        "url": f"https://spets.keycrm.app/app/orders/view/{main_order_id}",
    }


def upload_pdf_to_order(order_id: int, pdf_bytes: bytes, filename: str) -> bool:
    """
    Upload PDF as attachment to order. Optional — depends on KeyCRM API support.
    Currently KeyCRM API does not officially support file uploads to orders.
    We'll attach a link/note instead.
    """
    # Placeholder — KeyCRM API doesn't have file upload to orders yet.
    # We'll store the quote info in custom field OR_JOB_REF (already done in create_order).
    return False
